version: '3'
services:
    laravel.test:
        # image: webdevops/php-nginx:8.2-alpine
        image: ddl
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            TZ: 'America/Argentina/Buenos_Aires'
            # WEBROOT: '/var/www/public'
            WEB_DOCUMENT_ROOT: '/var/www/public'
            PHP_DISPLAY_ERRORS: '1'
            PHP_MEMORY_LIMIT: '2048M'
            PHP_MAX_EXECUTION_TIME: '-1'
        ports:
            - '${APP_PORT:-80}:80'
            - '5173:5173'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - '.:/var/www'
        networks:
            - sail
        depends_on:
            - mysql
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - PMA_ARBITRARY=1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
        networks:
            - sail
        depends_on:
            - mysql
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
